### ISSUE TITLE
Manual Enchantment Override in Config

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#100]
Have it so I can set what enchantments you get from what tired book, the level doesn't matter as you'll only be able to receive that specific enchantment from that tier.. but with a chance based on the levels? (Higher/max is of course more rare)

**Comment by cyberpwnn** [comment]
So just a complete manual override of everything?

**Comment by SwiftSwamp** [comment]
Yeah

**Comment by cyberpwnn** [comment]
#120

**Comment by cyberpwnn** [comment]
I want to have the ability to sort enchantments to what tiers I want.
Default for ya, I may be missing a few of the new ones,

Tier 1 - 4000xp
Cold Blooded
Deflect
Devil’s Grace
Forge
Nocturnal
Inferno (TNT)
Sticky (TNT)
Defusing (TNT)

Tier 2 - 8000xp
Beheading
Earthquake
Soulless
Alchemist
Blast (TNT)
Stamina

Tier 3 - 15000xp
Inferno
Longshot
Poison
Snare
Vampiric
Blessing
Demolition
Soul Stealer

Tier 4 - 25000xp
Frost
Nightmare
Soul Eruption
Empowerment
Reinforced
Anti-Gravity
Moss

Tier 5 - 40000xp
Rage
Shock

**Comment by SwiftSwamp** [comment]
Moved up to Urgent.

**Comment by SwiftSwamp** [comment]
Bumping again, this is really important.

**Comment by cyberpwnn** [comment]
You can configure the current plugin to do exact;y what you want it to do. Assume the example of 3 tiers

A, B and C

Set all A tiers to 1
Set all B tiers to 2000
Set all C tiers to 12000

Im working on a way you can type them all in manually.

**Comment by SwiftSwamp** [comment]
Sure but what about the costs of the actual tiers?

**Comment by cyberpwnn** [comment]
You can change the multiplier for that 

Manual will come soon

**Comment by SwiftSwamp** [comment]
By the way, what you provided above doesn't necessarily work, it still sorts random enchantments in different tiers.

**Comment by cyberpwnn** [comment]
You have to apply finesse. I explained how it works. Math can help you. But dont worry, ill make it manual :P

**Comment by cyberpwnn** [comment]
### Default config will look like this

``` yaml
enchantment:
  soulless:
    level-1: expert
  empowerment:
    level-1: expert
  drill:
    level-2: expert
    level-1: expert
    level-4: expert
    level-3: expert
    level-5: expert
  stamina:
    level-1: expert
  inferno:
    level-2: expert
    level-1: expert
    level-3: expert
  alchemist:
    level-1: expert
    level-3: expert
    level-2: expert
  frost:
    level-3: expert
    level-2: expert
    level-1: expert
  defused:
    level-3: expert
    level-2: expert
    level-1: expert
    level-5: expert
    level-4: expert
  longshot:
    level-1: expert
  shock:
    level-1: expert
    level-3: expert
    level-2: expert
  sticky:
    level-1: expert
  antigravity:
    level-1: expert
  poison:
    level-2: expert
    level-1: expert
  nocturnal:
    level-1: expert
  magnet:
    level-1: expert
  souleruption:
    level-3: expert
    level-1: expert
    level-2: expert
  blessing:
    level-1: expert
  beheading:
    level-5: expert
    level-3: expert
    level-4: expert
    level-1: expert
    level-2: expert
  demolition:
    level-1: expert
    level-2: expert
  moss:
    level-2: expert
    level-3: expert
    level-4: expert
    level-5: expert
    level-1: expert
  rage:
    level-2: expert
    level-1: expert
  doublestrike:
    level-1: expert
    level-2: expert
    level-3: expert
  blast:
    level-3: expert
    level-2: expert
    level-5: expert
    level-4: expert
    level-1: expert
  earthquake:
    level-3: expert
    level-2: expert
    level-1: expert
  deflect:
    level-1: expert
    level-2: expert
    level-3: expert
  forge:
    level-1: expert
  snare:
    level-1: expert
    level-2: expert
  soulstealer:
    level-1: expert
  irongrasp:
    level-1: expert
  vampiric:
    level-1: expert
    level-2: expert
  demolitionexpert:
    level-1: expert
  butcher:
    level-1: expert
    level-2: expert
    level-3: expert
  spring:
    level-1: expert
  nightmare:
    level-1: expert
  ender:
    level-1: expert
  devilsgrace:
    level-1: expert
  heatseeker:
    level-1: expert
  essence:
    level-1: expert
    level-2: expert
    level-3: expert
  reinforced:
    level-2: expert
    level-1: expert
  coldblooded:
    level-1: expert
tier:
  cost:
    scholar: 1024
    novice: 1024
    apprentice: 1024
    expert: 1024
    master: 1024
math:
  tiers:
  - apprentice
  - novice
  - scholar
  - expert
  - master
```
