### ISSUE TITLE
Blizzard Framework

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#121]
The Blizzard Framework is a Booster Like System to give temporary buffs to players on the server.

* Base Command: /blizzard, /blizzards, /booster, /boosters (Booster aliases as most people try that command by default)
* /blizzard check - Shows you the currently activated blizzard, however.. there should also possibly be a title menu screen that tells you a booster is activated? 
* ^ Instead.. possibly when you type /blizzard to open up the GUI with all of yours.. at the bottom it shows you all of the currently activate blizzard's and by who and time left?
* Blizzard's should announce in chat when there's.. 10, 5 and 1 minute left? maybe... 
* Blizzards are **prescient** so they save on shut down (This happens more than you think and encase so many people activate blizzards something doesn't happen).
* Blizzard's share the same MySQL Database so if you bought say a Fly Blizzard.. you could see that you have 1 Fly Blizzard left to activate on whatever server you join, however you can only use it on a single server.. so if you use it on Prison, you couldn't use it on Factions too.
* Add a per server blacklist as certain blizzards cannot be used on certain servers (i.e. McMMO Blizzards can't be used on Prison)
* Make sure Blizzard's stack so if multiple of the same are activated.. they'll add time (What happens if people try to activate blizzard's that aren't of the same tier, it just says "You must wait until the Tier 3 BLIZZARD finishes to use your tier 2!"? or something)
* You can have multiple different types of blizzard's running at the same time.
* The configuration defines the attributes of the blizzard's and times (Default, blizzard's will last 1 hour)
* 5 Different Tired Blizzard's, you can define the percentage boost in the config.

**Comment by cyberpwnn** [comment]
Make sure Blizzard's stack so if multiple of the same are activated.. they'll add time (What happens if people try to activate blizzard's that aren't of the same tier, it just says "You must wait until the Tier 3 BLIZZARD finishes to use your tier 2!"? or something)

Different tiers should do the same thing, just less long or less intense.

So they should always stack tiers

**Comment by cyberpwnn** [comment]
![image](https://cloud.githubusercontent.com/assets/10619135/19283623/a39bf894-8fc0-11e6-9967-d785578c81de.png)

**Comment by cyberpwnn** [comment]
``` yaml
# Example Boost Configuration
boosts:

  # There will be several of these by default
  pre-filled-boost-type: 

    # Customize the max level
    max-level: 3

    # Change the intensity ratio. 
    # INTENSITY = RATIO * LEVEL
    intensity-ratio: 0.25
    
    # Any servers in here will be the only ones that work
    # With this boost type. If empty, works on all servers
    whitelist: []
```
