### ISSUE TITLE
Multiple Server Selector Tweaks

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#271]
I'd like to be able to have the two servers in the secondary group window as if they were two completely different servers so I can customize different items, lores and the names for them. Right now it's a bit confusing :p And I can't explain the differences.. plus I'd like to use different items for them, this is urgent but not immediate.

**Comment by cyberpwnn** [comment]
but not immediate.

**Comment by cyberpwnn** [comment]
``` yaml
servers:
  skyblock:
    lore:
    - '&bMultiple servers and crap'
    - and stuff
    name: '&aSkyblock'
    y: 1
    x: 0
    members:
    - skyblock1
    - skyblock2
    material: SNOW_BALL
  skyblock2:
    material: MAGMA_CREAM
    members: []
    lore:
    - '&aBelow the down low.'
    name: '&cSkyblock South'
    y: 2
    x: 0
  saron:
    lore:
    - '&bIts an RPG Trillogy'
    name: '&cSaron'
    members:
    - saronGenisis
    - saronBlizzard
    - saronAwakening
    y: 1
    x: -1
    material: BLAZE_ROD
  factions:
    name: '&cFactions'
    lore:
    - '&bIts factions'
    - and stuff
    material: DIAMOND_SWORD
    y: 1
    x: 1
    members: []
  saronBlizzard:
    material: ICE
    x: 0
    y: 2
    lore:
    - '&bThe storm hits'
    name: '&cSaron Blizzard'
    members: []
  saronGenisis:
    lore:
    - '&bThe beginning'
    material: SAPLING
    name: '&cSaron Genisis'
    x: 0
    y: 1
    members: []
  saronAwakening:
    y: 3
    x: 0
    members: []
    lore:
    - '&bYou realize your power'
    material: FIREBALL
    name: '&cSaron Awakening'
  skyblock1:
    y: 1
    x: 0
    name: '&bSkyblock North'
    material: SLIME_BALL
    members: []
    lore:
    - '&aAbove the law'
style:
 
  # The background style for example 1:2, Stone:2, Stone
  gui-background: '160:7'
 
  # The name of the item in the hotbar
  hotbar-name: '&b&lServer Selector'
 
  # The item type held in the hotbar
  hotbar-item: compass
 
  # From slot 0-9, their hotbar slot to place the item in
  hotbar-slot: 0
 
  # Scale the gui viewport by height
  viewport: 4
```
