### ISSUE TITLE
Add Factions BossBar

### ISSUE THREAD

**Issue by GetDerpy** [cyberpwnn/GlacialRealms#284]
https://www.spigotmc.org/resources/factions-boss-bar-support-for-factionsuuid.14135/

**Comment by SwiftSwamp** [comment]
Boo, all of these new plugins.

**Comment by GetDerpy** [comment]
Default behaviour is fine. I think by default it shows faction name and power, but also whenever anyone logs on, off, kills or gets killed, it shows that info.

**Comment by SwiftSwamp** [comment]
Added, if you want to change the default messages let me know.. current config.

```
message: '%Color%Faction: %facName%&r Power: %facPower%'
infMessage: '%Color%Faction: %facName%'
allyColor: '&5'
truceColor: '&6'
ownColor: '&2'
neutralColor: '&f'
enemyColor: '&4'
time: 5
playerLogin:
  enabled: true
  time: 5
  message: '&3%player%&6 has logged on! &2%onlineMembers%/%totalMembers% &3members
    online'
playerLoginSelf:
  enabled: true
  time: 5
  message: '&2%landClaimed%/%givenPower% &3land claimed &2%onlineMembers%/%totalMembers%
    &3members online'
playerLogOff:
  enabled: true
  time: 5
  message: '&3%player%&4 has logged off &2%onlineMembers%/%totalMembers% &3members
    online'
playerDeath:
  enabled: true
  time: 5
  message: '&3%player%&4 has died to &3%killer% &4from &3%faction%'
playerKiller:
  enabled: true
  time: 5
  message: '&3%killer%&4 has killed &3%playerKilled% &4from &3%faction%'

```
