### ISSUE TITLE
Effex GUI Cosmetic Bug

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#291]
The cosmetic bug where Novice is showing before Apprentice is still happening.
Could I also get the full list of every enchantment and their max levels or is there somewhere I can view this as the new default config only had about 21 out of the 41 total enchantments.

**Comment by SwiftSwamp** [comment]
I'd pull out each piece and just do /enchantapi all or /enchantall, whatever the command is but it just hasn't been working for quite some time.

**Comment by cyberpwnn** [comment]
As for missing enchantments, what? it shows all registered custom enchantments except for Hells curse.

As for the order... what? Are you using the latest version?

**Comment by SwiftSwamp** [comment]
I'm referring to the actual levels, I have no clue what the max level of an enchantment is, there's no list anywhere. The new config you made with the update for manually writing it out only had 21/41 enchantments in it.

**Comment by cyberpwnn** [comment]
Did you delete the config.yml? Try that. This is what your default configuration **SHOULD** look like.

``` yaml
enchantment:
  soulless:
    level-1: expert
  empowerment:
    level-1: expert
  drill:
    level-2: expert
    level-1: expert
    level-4: expert
    level-3: expert
    level-5: expert
  stamina:
    level-1: expert
  inferno:
    level-2: expert
    level-1: expert
    level-3: expert
  alchemist:
    level-1: expert
    level-3: expert
    level-2: expert
  frost:
    level-3: expert
    level-2: expert
    level-1: expert
  defused:
    level-3: expert
    level-2: expert
    level-1: expert
    level-5: expert
    level-4: expert
  longshot:
    level-1: expert
  shock:
    level-1: expert
    level-3: expert
    level-2: expert
  sticky:
    level-1: expert
  antigravity:
    level-1: expert
  poison:
    level-2: expert
    level-1: expert
  nocturnal:
    level-1: expert
  magnet:
    level-1: expert
  souleruption:
    level-3: expert
    level-1: expert
    level-2: expert
  blessing:
    level-1: expert
  beheading:
    level-5: expert
    level-3: expert
    level-4: expert
    level-1: expert
    level-2: expert
  demolition:
    level-1: expert
    level-2: expert
  moss:
    level-2: expert
    level-3: expert
    level-4: expert
    level-5: expert
    level-1: expert
  rage:
    level-2: expert
    level-1: expert
  doublestrike:
    level-1: expert
    level-2: expert
    level-3: expert
  blast:
    level-3: expert
    level-2: expert
    level-5: expert
    level-4: expert
    level-1: expert
  earthquake:
    level-3: expert
    level-2: expert
    level-1: expert
  deflect:
    level-1: expert
    level-2: expert
    level-3: expert
  forge:
    level-1: expert
  snare:
    level-1: expert
    level-2: expert
  soulstealer:
    level-1: expert
  irongrasp:
    level-1: expert
  vampiric:
    level-1: expert
    level-2: expert
  demolitionexpert:
    level-1: expert
  butcher:
    level-1: expert
    level-2: expert
    level-3: expert
  spring:
    level-1: expert
  nightmare:
    level-1: expert
  ender:
    level-1: expert
  devilsgrace:
    level-1: expert
  heatseeker:
    level-1: expert
  essence:
    level-1: expert
    level-2: expert
    level-3: expert
  reinforced:
    level-2: expert
    level-1: expert
  coldblooded:
    level-1: expert
tier:
  cost:
    scholar: 1024
    novice: 1024
    apprentice: 1024
    expert: 1024
    master: 1024
math:
  tiers:
  - apprentice
  - novice
  - scholar
  - expert
  - master

```
