### ISSUE TITLE
Increase Jackpot Bids

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#408]
Jackpot bids need to be increased and adjusted based on the server type.

**Comment by kotik1998** [comment]
me /jp like high bid at 1 mil not some 10k :P

**Comment by Puretie** [comment]
Adding stale tag due to lack of progress following the three day rule. Please allow yourself twenty minutes to see this issue through, @SwiftSwamp

**Comment by SwiftSwamp** [comment]
Planning out the prices based on the server now.

**Comment by SwiftSwamp** [comment]
### Changed Coinflips minimum bets to the following and tax rate: ###
* There is now a 5% => 10% tax for Coinflips on all servers.
* KitPvP Minimum Bet: $5 => $25
* Factions/Skyblock Minimum Bet: $5 => $5,000
* Prison Minimum Bet: $5 => $1,000,000

### Changed Rock, Paper, Scissors minimum bets to the following and tax rate: ###
* There is now a 5% => 10% tax for all RPS on all servers
* KitPvP Minimum RPS: $5 => $25
* Factions/Skyblock Minimum RPS: $5 => $5,000
* Prison Minimum RPS: $5 => $1,000,000

### Set Jackpot minimum bets to the following and tax rate: ###
* There is now a 5% => 10% tax for all Jackpots on all servers

```
prison:
  low:
    firstbet: 1000000.0
    secondbet: 5000000.0
    thirdbet: 15000000.0
    fourthbet: 25000000.0
    maxbet: 1000000000.0
  medium:
    firstbet: 10000000.0
    secondbet: 50000000.0
    thirdbet: 150000000.0
    fourthbet: 250000000.0
    maxbet: 100000000000.0
  high:
    firstbet: 1000000000.0
    secondbet: 5000000000.0
    thirdbet: 15000000000.0
    fourthbet: 25000000000.0
    maxbet: 10000000000000.0
```
