### ISSUE TITLE
Information & News Hub

### ISSUE THREAD

**Issue by cyberpwnn** [cyberpwnn/GlacialRealms#460]
### Generally Speaking...
The info hub will be based in github. Essentially, each file has a date on it, with logged information on each line. Each line must have a date, key, author, and description.

On the server side, each player has a last-viewed data file showing the last date they viewed the logs. Commune then downloads the news and information files they have not seen into a cache for viewing by the player via gui. All information is streamed to the server from github and is live.

### File Syntax and Enhancements 
The file name must be a date and only a date. Here are some examples: 
* ```11-13-16.yml``` (as November 13th, 2016)
* ```1479034299855.yml``` (as November 13th, 2016)

Each logged line must follow the following syntax
``` yaml
some-tag-for-this-event:
- @a [author]
- @t [time]
- @r [link]
- @s [server-partial-name, other-server-partial-name] || [all]
- ! [Warning text (with symbol)] # This is basically orange
- + [Added something]   (green)
- - [Removed crap]          (red)
- * [Changed something] (yellow)
- i [Sub information (italic gray text)]
```

---

Here is the syntax definition for each tag
* ```@a [author]```: Case & Color/Formatting is allowed (ex: &c&lcyberpwn)
* ```@t [time]```: 12/24h time. 12h time needs am/pm appended at the end (ex: 4:35pm)
* ```@r [link]```: The link reference (when clicked opens browser)
* ```@s [servers]```: Includes applicable servers (using skyblock would do all servers containing the characters skybkick (skyblock and skyblock2)). You can also use commas, for example, ```@s skyblock, factions``` would include skyblock 1&2 + factions. You can also use ```@s all``` for simplicity
* ```[description]```: Supports Placeholders, colors, and formatting. 

### Working Example
File Name: ```11-13-2016.yml```

---

``` yaml
chameleon-in-3rd-person-fixed:
- @a &d&lcyberpwn
- @t 3:00am
- @r https://github.com/cyberpwnn/GlacialRealms/issues/420
- &aThe Chameleon ability now works in third person
- &eNote: Third person normal is how the color is seen (reverse third may look weird)

chameleon-tweaks:
- @a &d&lcyberpwn
- @t 3:20am
- @r https://github.com/cyberpwnn/GlacialRealms/issues/421
- &aThe Chameleon ability now works faster
```
