### ISSUE TITLE
Non Custom Count Relative ignored

### ISSUE THREAD

**Issue by cyberpwnn** [cyberpwnn/GlacialRealms#53]
Relative is completely ignored if you do not have custom count enabled (Idk if you fixed this yet and just haven't pushed the version for me).

**Comment by SwiftSwamp** [comment]
This was never actually fixed. Still happens.

**Comment by SwiftSwamp** [comment]
Nvm, I see why it's not working. This is going to be annoying, I cri .-.
The relative isn't sorted per grouped items.. so if you have multiple different sub category's with the relative of say 5, 10 and 15.. they'll conflict even though they're not in the same group. Oh well.

**Comment by SwiftSwamp** [comment]
Actually nevermind, it's not sorting..

**Comment by SwiftSwamp** [comment]
Here's the configuration I'm using for one of them, some randomly sort and others do not. I have no clue how it's sorting it..

```
shop:
  ui:
    categories:
      ranks:
        items:
          be71b819-0ca1-4dcc-865a-5d03ce723752:
            material: NETHER_STAR:0
            name: '&l&bFrost Rank'
            unlock-sound: CLICK
            lore:
            - '&cTemporarily Unavailable'
            sell: 0.0
            commands:
            - pex user %player% group add Frost
            relative: 5
            required-slots: 0
            cost: 0.0
          e605f206-9ad0-4813-afca-f870af5390f0:
            material: NETHER_STAR:0
            name: '&l&bIce Rank'
            unlock-sound: CLICK
            lore:
            - '&cTemporarily Unavailable'
            sell: 0.0
            commands:
            - pex user %player% group remove Frost
            - pex user %player% group add Ice
            relative: 10
            required-slots: 0
            cost: 0.0
          2e195928-9d13-40a4-96bb-59793833d498:
            material: NETHER_STAR:0
            name: '&l&bArctic Rank'
            unlock-sound: CLICK
            lore:
            - '&cTemporarily Unavailable'
            sell: 0.0
            commands:
            - pex user %player% group remove Ice
            - pex user %player% group add Arctic
            relative: 15
            required-slots: 0
            cost: 0.0
          76a9c87c-ebcc-4871-8896-f8fb3bf9d61d:
            material: NETHER_STAR:0
            name: '&l&bBlizzard Rank'
            unlock-sound: CLICK
            lore:
            - '&cTemporarily Unavailable'
            sell: 0.0
            commands:
            - pex user %player% group remove Arctic
            - pex user %player% group add Blizzard
            relative: 20
            required-slots: 0
            cost: 0.0
          6233542c-9a86-4b13-89da-23d2ca6dc778:
            material: NETHER_STAR:0
            name: '&l&bGlacial Rank'
            unlock-sound: CLICK
            lore:
            - '&cTemporarily Unavailable'
            sell: 0.0
            commands:
            - pex user %player% group remove Blizzard
            - pex user %player% group add Glacial
            relative: 25
            required-slots: 0
            cost: 0.0
        x: -4
        y: 2
        lore: []
        name: '&e&lRanks'
        material: NETHER_STAR:0
      rankupgrades:
        items:
          54168cb9-cc45-4fa6-b630-9b60b2f1faf4:
            material: NETHER_STAR:0
            name: '&l&bFrost => Ice Rank Upgrade'
            unlock-sound: CLICK
            lore:
            - '&cTemporarily Unavailable'
            sell: 0.0
            commands:
            - pex user %player% group remove Frost
            - pex user %player% group add Ice
            relative: 100
            required-slots: 0
            cost: 0.0
          35193312-66c7-4c74-9156-7462324ccd95:
            material: NETHER_STAR:0
            name: '&l&bIce => Arctic Rank Upgrade'
            unlock-sound: CLICK
            lore:
            - '&cTemporarily Unavailable'
            sell: 0.0
            commands:
            - pex user %player% group remove Ice
            - pex user %player% group add Arctic
            relative: 110
            required-slots: 0
            cost: 0.0
          d5320fa7-dbbb-43a2-958f-becda461b412:
            material: NETHER_STAR:0
            name: '&l&bArctic => Blizzard Rank Upgrade'
            unlock-sound: CLICK
            lore:
            - '&cTemporarily Unavailable'
            sell: 0.0
            commands:
            - pex user %player% group remove Arctic
            - pex user %player% group add Blizzard
            relative: 120
            required-slots: 0
            cost: 0.0
          b8ec44c0-181a-4624-8ff4-8957c2d0ef68:
            material: NETHER_STAR:0
            name: '&l&bBlizzard => Glacial Rank Upgrade'
            unlock-sound: CLICK
            lore:
            - '&cTemporarily Unavailable'
            sell: 0.0
            commands:
            - pex user %player% group remove Blizzard
            - pex user %player% group add Glacial
            relative: 130
            required-slots: 0
            cost: 0.0
        x: -3
        y: 2
        lore: []
        name: '&e&lRank Upgrades'
        material: NETHER_STAR:0
      titles:
        items:
          b8ec44c0-181a-4624-8ff4-8957c2d0ef68:
            material: NAME_TAG:0
            name: '&l&b#BooSwift Title'
            unlock-sound: CLICK
            lore:
            - '&a%cost% Credits'
            - '&7Left Click to Buy'
            sell: 0.0
            commands:
            - title give %player% #BooSwift
            relative: 2000
            required-slots: 0
            cost: 5.0
        x: -2
        y: 2
        lore: []
        name: '&e&lTitles'
        material: NAME_TAG:0
      limitededitiontitles:
        items:
          30c3ed3e-2b90-4c69-81bd-176f9e223514:
            material: NAME_TAG:0
            name: '&l&bChristmas Title'
            unlock-sound: CLICK
            lore:
            - '&a%cost% Credits'
            - '&7Left Click to Buy'
            sell: 0.0
            commands:
            - title give %player% Christmas
            relative: 3000
            required-slots: 0
            cost: 7.0
        x: -1
        y: 2
        lore: []
        name: '&e&lLimited Edition Titles'
        material: NAME_TAG:0
      cratekeys:
        items:
          c0fd7dde-9481-11e6-ae22-56b6b6499611:
            material: NETHER_STAR:0
            name: '&l&bCrystal Crate Key'
            unlock-sound: CLICK
            lore:
            - '&a%cost% Credits'
            - '&7Left Click to Buy'
            sell: 0.0
            commands:
            - crate givekey %player% Crystal 1
            relative: 4000
            required-slots: 1
            cost: 3.0
          da67cd7c-e18c-4187-a748-415ed21fe445:
            material: NETHER_STAR:0
            name: '&l&bFrozen Crate Key'
            unlock-sound: CLICK
            lore:
            - '&a%cost% Credits'
            - '&7Left Click to Buy'
            sell: 0.0
            commands:
            - crate givekey %player% Frozen 1
            relative: 4010
            required-slots: 1
            cost: 5.0
          c30ab246-beeb-447e-975a-b5bd2772bcfe:
            material: NETHER_STAR:0
            name: '&l&bGlacial Crate Key'
            unlock-sound: CLICK
            lore:
            - '&a%cost% Credits'
            - '&7Left Click to Buy'
            sell: 0.0
            commands:
            - crate givekey %player% Glacial 1
            relative: 4020
            required-slots: 1
            cost: 10.0
        x: 0
        y: 2
        lore: []
        name: '&e&lCrate Keys'
        material: ENDER_CHEST:0
      kits:
        items:
          c0fd7dde-9481-11e6-ae22-56b6b6499611:
            material: SNOW_BALL:0
            name: '&l&bSnow Kit'
            unlock-sound: CLICK
            lore:
            - '&a%cost% Credits'
            - '&7Left Click to Buy'
            sell: 0.0
            commands:
            - sync pex user %player% add essentials.kits.snow
            relative: 5000
            required-slots: 0
            cost: 10.0
          fc52833c-d3da-4d04-8fc2-7a1491d6dee1:
            material: DRAGON_EGG:0
            name: '&l&bDragon Kit'
            unlock-sound: CLICK
            lore:
            - '&a%cost% Credits'
            - '&7Left Click to Buy'
            sell: 0.0
            commands:
            - sync pex user %player% add essentials.kits.dragon
            relative: 5010
            required-slots: 0
            cost: 10.0
          29bebbf4-f81f-446a-8a5c-decda30f7df9:
            material: DIAMOND_SWORD:0
            name: '&l&bFrostbite Kit'
            unlock-sound: CLICK
            lore:
            - '&a%cost% Credits'
            - '&7Left Click to Buy'
            sell: 0.0
            commands:
            - sync pex user %player% add essentials.kits.frostbite
            relative: 5020
            required-slots: 0
            cost: 10.0
          38843622-2566-4cd0-bc04-42271d6c17f6:
            material: ICE:0
            name: '&l&bFrozen Kit'
            unlock-sound: CLICK
            lore:
            - '&a%cost% Credits'
            - '&7Left Click to Buy'
            sell: 0.0
            commands:
            - sync pex user %player% add essentials.kits.frozen
            relative: 5030
            required-slots: 0
            cost: 10.0
          21529356-c7ab-41f4-9ef6-2d33b0aa07aa:
            material: POTION:0
            name: '&l&bPotions Kit'
            unlock-sound: CLICK
            lore:
            - '&a%cost% Credits'
            - '&7Left Click to Buy'
            sell: 0.0
            commands:
            - sync pex user %player% add essentials.kits.potions
            relative: 5040
            required-slots: 0
            cost: 10.0
          adb9f6d0-0456-4551-a1e9-496091334800:
            material: TNT:0
            name: '&l&bRaid Kit'
            unlock-sound: CLICK
            lore:
            - '&a%cost% Credits'
            - '&7Left Click to Buy'
            sell: 0.0
            commands:
            - sync pex user %player% add essentials.kits.raid
            relative: 5050
            required-slots: 0
            cost: 10.0
        x: 1
        y: 2
        lore: []
        name: '&e&lKits'
        material: DIAMOND_SWORD:0
      sellboosters:
        items:
          1c63ea13-2340-4e87-bde2-8bb2d26a8b24:
            material: EXP_BOTTLE:0
            name: '&l&b2x Global Sell Booster (1 Hour)'
            unlock-sound: CLICK
            lore:
            - '&a%cost% Credits'
            - '&7Left Click to Buy'
            sell: 0.0
            commands:
            - multi giveglobal 2 3600 %player%
            relative: 5
            required-slots: 1
            cost: 6000.0
          4bab6930-e715-495c-a312-383b537c74e8:
            material: EXP_BOTTLE:0
            name: '&l&b3x Global Sell Booster (1 Hour)'
            unlock-sound: CLICK
            lore:
            - '&a%cost% Credits'
            - '&7Left Click to Buy'
            sell: 0.0
            commands:
            - multi giveglobal 3 3600 %player%
            relative: 10
            required-slots: 1
            cost: 6010.0
          c7c00d33-35e4-4109-919a-19a1f9ab1ff3:
            material: EXP_BOTTLE:0
            name: '&l&b4x Global Sell Booster (1 Hour)'
            unlock-sound: CLICK
            lore:
            - '&a%cost% Credits'
            - '&7Left Click to Buy'
            sell: 0.0
            commands:
            - multi giveglobal 4 3600 %player%
            relative: 6020
            required-slots: 1
            cost: 25.0
          58ae0103-c2b4-4c3f-8804-7c6ffe93a39e:
            material: EXP_BOTTLE:0
            name: '&l&b5x Global Sell Booster (1 Hour)'
            unlock-sound: CLICK
            lore:
            - '&a%cost% Credits'
            - '&7Left Click to Buy'
            sell: 0.0
            commands:
            - multi giveglobal 5 3600 %player%
            relative: 6030
            required-slots: 1
            cost: 35.0
        x: 2
        y: 2
        lore: []
        name: '&e&lSell Boosters'
        material: DIAMOND_PICKAXE:0
      skillboosters:
        items:
          fffce6e8-9d4d-4453-a064-4767e4de7dad:
            material: GOLDEN_APPLE:0
            name: '&l&b(1 Day) 100% XP Booster'
            unlock-sound: CLICK
            lore:
            - '&a%cost% Credits'
            - '&7Left Click to Buy'
            sell: 0.0
            commands:
            - x giveboost 1 1728000 %player%
            relative: 7000
            required-slots: 1
            cost: 5.0
          5dece3b4-792d-4a60-998c-af0eb945d764:
            material: GOLDEN_APPLE:0
            name: '&l&b(1 Day) 400% XP Booster'
            unlock-sound: CLICK
            lore:
            - '&a%cost% Credits'
            - '&7Left Click to Buy'
            sell: 0.0
            commands:
            - x giveboost 4 1728000 %player%
            relative: 7010
            required-slots: 1
            cost: 10.0
          8ef8581d-cefa-4bf0-af31-0623beb6cc27:
            material: GOLDEN_APPLE:1
            name: '&l&b(7 Day) 100% XP Booster'
            unlock-sound: CLICK
            lore:
            - '&a%cost% Credits'
            - '&7Left Click to Buy'
            sell: 0.0
            commands:
            - x giveboost 1 12096000 %player%
            relative: 7020
            required-slots: 1
            cost: 15.0
          d75323fb-30c8-4bb3-a5c0-e765e31a5f76:
            material: GOLDEN_APPLE:1
            name: '&l&b(7 Day) 400% XP Booster'
            unlock-sound: CLICK
            lore:
            - '&a%cost% Credits'
            - '&7Left Click to Buy'
            sell: 0.0
            commands:
            - x giveboost 4 12096000 %player%
            relative: 7030
            required-slots: 1
            cost: 20.0
        x: 3
        y: 2
        lore: []
        name: '&e&lSkill Boosters'
        material: GOLDEN_APPLE:1
      blackmarket:
        items:
          c0fd7dde-9481-11e6-ae22-56b6b6499611:
            material: NAME_TAG:0
            name: '&l&bItem Rename Tag'
            unlock-sound: CLICK
            lore:
            - '&a%cost% Credits'
            - '&7Left Click to Buy'
            sell: 0.0
            commands:
            - namemyitem give %player%
            relative: 8000
            required-slots: 1
            cost: 3.0
        x: 4
        y: 2
        lore: []
        name: '&e&lBlack Market'
        material: COAL:0
 
    # This title of the window for the shop
    title: '&b&lGlacial Credit Shop'
 
    # Allow the player to use different amounts.
    # use %amount% for the amount they selected.
    # The cost is calculated as COST x %amount%. Set the price of 1 item.
    custom-count: false
 
  # This is the description of the shop
  description: '&b&lGlacial Credit Shop'
 
  # This is the currency file name in the currencies folder. 
  # DO NOT add .yml to the end of it.
  currency: credits
 
  # This is the Display name of the shop.
  # Supports color codes
  display-name: '&b&lGlacial Credit Shop'
  viewport: 3
  aliases:
  - vouchershop
  - creditsshop
  - vouchersshop
```
