### ISSUE TITLE
Should the Intensity value be configurable?

### ISSUE THREAD

**Issue by cyberpwnn** [cyberpwnn/GlacialRealms#6]
Would it be a good idea to configure the intensity values of enchantments to determine how it should be categorized? That way it is semi automatic but not completely? The configuration would look something like this for intensity

``` yaml
intensity:
  durability: 0.7
  protection: 0.45
  shock: 0.784
  fire-aspect: 0.87
  inferno: 0.87
```

This would be calculated like so

![eqn9716](https://cloud.githubusercontent.com/assets/10619135/18819910/895a011c-8366-11e6-829b-8306082770d9.png)

Where as
- i = The intensity factor used for judging intensity
- b = The base value supplied in the config
- l = The level of the given enchantment
