### ISSUE TITLE
NewsHub Word Wrapping

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#667]
The NewsHub needs better word wrapping, anytime I use any of the symbols / characters used to determine what the line is it acts as if it's another new one,.

**Comment by cyberpwnn** [comment]
I dont understand.

**Comment by SwiftSwamp** [comment]
log-1482001103616:
- /l Title Updates
- /a SwiftSwamp
- /m NAME_TAG
- a Daily #2016, #2017, NewYearNewMe and DropTheBall Titles
- a Hello, this is a test.

Anything after the pound sign just won't show.
The "a" in the "Hello, this is a test" will start a new line at the "a test" with "test".

**Comment by SwiftSwamp** [comment]
Suggested solution, ignore all symbols / formatting for the News Hub in anything between quotes, i.e. a "Hello, this is a test. New Title is #2017!"

**Comment by cyberpwnn** [comment]
``` yaml
this:
  is:
    a: 
      string: 'sdfs df sdf sdfs df'
      number: 434
      decimal: 0.4343
      list: 
      - dfdf
      - dsfdf
      boolean: false
      # comment
```
